apiVersion: v1
kind: Pod
metadata:
  name: postgres
spec:
  containers:
  - name: postgres
    image: postgres
    env:
    - name: POSTGRES_USER
      value: admin
    - name: POSTGRES_PASSWORD
      value: mysecretpassword
    ports:
    - containerPort: 5432
