version: "3"
services:
  app:
    build: ./app
    image: restapipv
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql:8.0.21
    ports:
      - "3306:3306"
    command: --init-file /data/init.sql
    volumes:
      - ./db/init.sql:/data/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: root 